name: Build ARM64 RescueZilla ISO

on: [push]

jobs:
  rescuezilla-iso-build-arm64:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [arm64]
        release: [jammy, noble, oracular]  # 添加需要构建的Ubuntu版本

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive
          lfs: true
          fetch-depth: 0

      # 配置交叉编译环境
      - name: Setup cross-build tools
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-user-static binfmt-support crossbuild-essential-arm64

      # 构建ARM64 Docker镜像
      - name: Build multi-arch Docker image
        run: |
          docker buildx create --use
          docker buildx build \
            --platform linux/arm64 \
            -t rescuezilla-builder-arm64 \
            --load \
            .

      # 在容器内执行交叉编译
      - name: Build ISO in container
        run: |
          docker run --rm --platform linux/arm64 \
            -v ${{ github.workspace }}:/workspace \
            -w /workspace \
            rescuezilla-builder-arm64 \
            /bin/bash -c "\
              make clean-all && \
              ARCH=${{ matrix.arch }} UBUNTU_CODENAME=${{ matrix.release }} make iso"

      # 整理产物
      - name: Organize artifacts
        run: |
          mkdir -p completed-artifacts/arm64
          sudo mv build/rescuezilla.${{ matrix.arch }}.${{ matrix.release }}.iso \
            completed-artifacts/arm64/rescuezilla-${{ github.ref_name }}-arm64.${{ matrix.release }}.iso

      # 创建校验和
      - name: Create checksums
        run: |
          cd completed-artifacts/arm64 && \
          sha256sum * > SHA256SUM && \
          md5sum * > MD5SUM

      # 上传产物
      - uses: actions/upload-artifact@v4
        with:
          name: arm64-isos
          path: |
            completed-artifacts/arm64/SHA256SUM
            completed-artifacts/arm64/MD5SUM
            completed-artifacts/arm64/*.iso

      # 发布到GitHub Release (仅限标签推送)
      - name: Upload release assets
        if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: completed-artifacts/arm64/*

# 保留原有x86构建流程（可选）
# 原有x86构建步骤可保持不动，与ARM构建形成矩阵策略
